language: python
python:
  - "2.7"
install:
  - python setup.py install
  - pip install coverage
script:
  - coverage run --source dicomtools -m unittest discover -s ./tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
